SOURCES=dynArray.ml util.ml ast.mli ast2.mli codegen.ml print_ast2.ml compiler_state.ml expand_ast.ml parser.mly lexer.mll ssa.ml compile.ml main.ml
RESULT=slcompiler

# Use native code by default
# Run: make byte-code for byte code compilation
all: native-code

include OCamlMakefile
